name: calculator_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  function_tree: 0.8.13
  auto_size_text: 3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  web: 
    image_path: path/to/image.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: path/to/image.png
    generate: true
    icon_size: 48
  ios: true
  min_sdk_android: 19

flutter: 
  uses-material-design: true

